### ISSUE TITLE
Not possible to display umlaute in bootstrap template

### ISSUE THREAD

**Issue by samuelstein** [jjbgf/eventbooking#10]

**Comment by samuelstein** [comment]
directly in template?

**Comment by numberpi** [comment]
Yes, in the template file.

**Comment by samuelstein** [comment]
ok. it's really working. problem was, that my local file encoding wasn't utf-8. windows....

**Comment by samuelstein** [comment]
Another problem is utf8 characters in views.py due python 2.7.
See: http://stackoverflow.com/a/1342079
Added: ´# -_\- coding: utf-8 -_-#´
